### ISSUE TITLE
Dashboard not working

### ISSUE THREAD

**Issue by hechth** [martenson/public-galaxy-servers#25]
The dashboard https://stats.galaxyproject.eu/d/000000020/public-galaxy-servers?orgId=1 doesn't work - is this repo still maintained @martenson or did this move somewhere else?

**Comment by hexylena** [comment]
I was responsible for running this on EU and it worked while I was there. Now I guess @mira-miracoli @sanjaysrikakulam are responsible for why it isn't working. It used to be a process running directly on the grafana VM that provided data for that dashboard. It'd be super cool to have it running again

**Comment by hechth** [comment]
@hexylena yeah I agree - getting an idea of where a Galaxy instance is on a map is super useful!

Did the code move house or is it still in this repo?

**Comment by hexylena** [comment]
no nothing moved. This code just collects the information and aggregates it, ready for grafana and influxdb ingestion. The process running that needs to be on grafanas VM in the current setup.

**Comment by sanjaysrikakulam** [comment]
The `json_dir` (`pgs_web_dir`) was not getting created due to permission error. I manually made it (set it to 777, which is not ideal) for testing and ran the cron job. Now the dashboard is updated. I will keep an eye on and add a task to our [pgs](https://github.com/usegalaxy-eu/infrastructure-playbook/tree/master/roles/pgs) role to set up the proper permissions. 

May I ask how this [list](https://galaxyproject.org/use/feed.json) is updated? Looks like the list needs to be updated because I see lots of request errors and this is probably due to the non-existence of the probed site.

Also the [URL here](https://github.com/martenson/public-galaxy-servers/tree/master#running-the-parser) in this section pointing to the dashboard needs an update.

**Comment by hexylena** [comment]
Ahh easy fix at least.

> May I ask how this [list](https://galaxyproject.org/use/feed.json) is updated? Looks like the list needs to be updated because I see lots of request errors and this is probably due to the non-existence of the probed site.

Yes, it's just whichever sites are listed in https://github.com/galaxyproject/galaxy-hub/tree/master/content/use, it is expected that there are a *lot* of request errors, that is normal. Some sites aren't public (and aren't filtered out), some are old and deprecated. It would be nice to eventually prune that list, but that's more likely to cause protracted discussion for a small benefit (and I guess the project likes the large number of servers listed there.)

**Comment by hexylena** [comment]
URL is fixed in readme, good catch @sanjaysrikakulam !

**Comment by sanjaysrikakulam** [comment]
Cool, thank you for the info. This issue can be closed.

**Comment by hexylena** [comment]
Thanks so much for fixing it @sanjaysrikakulam, it's appreciated!
